def compoundinterest(p,r,t,n):
    print(f"The Principle Amount is {p}")
    print(f"The Rate is {r}")
    print(f"The Time is {t}")
    print(f"The No. of Times Interest is Compounded is {n}")
    ci=p*((1+(r/n))**(n*t))
    print(f"The Compound Interest is {ci}")
p=int(input("Enter The Principle Amount:"))
r=int(input("Enter The Rate:"))
t=int(input("Enter The Time:"))
n=int(input("Enter The No. of Times Interest is Compounded:"))
compoundinterest(p,r,t,n)