def volumnofrectangularprism(w,h,l):
    print(f"The Width is {w}")
    print(f"The Height is {h}")
    print(f"The Length is {l}")
    volumn=(w*h*l)
    print(f"The volumn of Rectangular Prism:{volumn}")
w=int(input("Enter The Width of Rectangular Prism:"))
h=int(input("Enter The Height of Rectangular Prism:"))
l=int(input("Enter The Length of Rectangular Prism:"))
volumnofrectangularprism(w,h,l)